/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005313",
        "error": "#ba1a1a",
        "tertiary-container": "#00397c",
        "on-primary-fixed": "#001a40",
        "on-primary": "#ffffff",
        "on-secondary-container": "#00731e",
        "secondary-fixed": "#84fc84",
        "on-tertiary-container": "#79a5f7",
        "on-surface": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#d7e2ff",
        "surface-tint": "#425e91",
        "error-container": "#ffdad6",
        "tertiary": "#002453",
        "inverse-surface": "#313030",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f6f3f2",
        "secondary-container": "#81f982",
        "on-error": "#ffffff",
        "on-surface-variant": "#44474f",
        "surface-container-high": "#eae7e7",
        "outline": "#747780",
        "surface": "#fcf9f8",
        "primary-container": "#1b3a6b",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#acc7ff",
        "primary": "#002452",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f0eded",
        "surface-bright": "#fcf9f8",
        "on-primary-container": "#89a5dd",
        "surface-variant": "#e5e2e1",
        "primary-fixed-dim": "#acc7ff",
        "outline-variant": "#c4c6d0",
        "on-tertiary-fixed": "#001a40",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#67df6b",
        "on-background": "#1c1b1b",
        "primary-fixed": "#d7e2ff",
        "tertiary-fixed-dim": "#acc7ff",
        "background": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed": "#002204",
        "secondary": "#006e1d",
        "on-primary-fixed-variant": "#294678",
        "on-tertiary-fixed-variant": "#044491"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "base": "8px",
        "section-gap": "80px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
